services:
  - type: web
    name: txt uploader
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/pkvgithub/myrepo
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        sync: false  # Default port value, update if needed
